---
# Update for your Foreman and Puppet master hostname(s)
:url: "http://master.olindata.vm:3000"
:ssl_ca: "/etc/puppetlabs/puppet/ssl/certs/ca.pem"
:ssl_cert: "/etc/puppetlabs/puppet/ssl/certs/master.olindata.vm.pem"
:ssl_key: "/etc/puppetlabs/puppet/ssl/private_keys/master.olindata.vm.pem"

# Advanced settings
:puppetdir: "/opt/puppetlabs/server/data/puppetserver"
:puppetuser: "puppet"
:facts: true
:timeout: 10
:threads: null
