---
roles:
  pe-puppet-master:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 8192]
    provisioners:
      -
        type: hosts
        add_localhost_hostnames: false
        sync_hosts: true
      - type: shell
        inline: |-
          /bin/systemctl stop firewalld
      -
        type: pe_bootstrap
        role: !ruby/sym master
      -
        type: shell
        inline: |-
          /usr/local/bin/puppet module install zack-r10k --version 3.2.0
          /usr/local/bin/puppet module install abrader-gms --version 1.0.2
          /usr/local/bin/puppet apply /vagrant/manifests/r10k_installation.pp
          /usr/local/bin/r10k deploy environment -pv
          /bin/echo '==> puppet config set hiera_config /etc/puppetlabs/code/environments/production/hiera.yaml'
          /usr/local/bin/puppet config set hiera_config /etc/puppetlabs/code/environments/production/hiera.yaml
          /bin/echo '==> /bin/systemctl restart pe-puppetserver'
          /bin/systemctl restart pe-puppetserver
          /bin/echo '==> /usr/local/bin/puppet agent -t'
          /usr/local/bin/puppet agent -t || true
          /sbin/service puppet stop

  foss-puppet-master:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 6144]
    provisioners:
      -
        type: hosts
        add_localhost_hostnames: false
        sync_hosts: true
      - type: shell
        inline: |-
          /bin/echo '==> Disabling firewall'
          /bin/systemctl stop firewalld
          /bin/systemctl disable firewalld
          /bin/yum install -y -q https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm epel-release
          /bin/yum install -y -q puppetserver
          /opt/puppetlabs/bin/puppet module install puppetlabs/puppetdb --version 5.1.2
          /opt/puppetlabs/bin/puppet module install puppetlabs/vcsrepo --version 1.3.2
          /opt/puppetlabs/bin/puppet module install zack/r10k --version 3.2.0
          /opt/puppetlabs/bin/puppet module install abrader/gms --version 1.0.2
          /opt/puppetlabs/bin/puppet module install ajcrowe/supervisord --ignore-dependencies --version 0.6.0

  pe-puppet-agent:
    provisioners:
      -
        type: hosts
        add_localhost_hostnames: false
        sync_hosts: true
      -
        type: pe_agent
        master_vm: !ruby/sym master
      -
        type: shell
        inline: |-
          /sbin/service puppet stop

  pe-puppet-agent-2g:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 2048]
    provisioners:
      -
        type: hosts
        add_localhost_hostnames: false
        sync_hosts: true
      -
        type: pe_agent
        master_vm: !ruby/sym master
      -
        type: shell
        inline: |-
          /sbin/service puppet stop

  foss-puppet-agent:
    provisioners:
      -
        type: hosts
        add_localhost_hostnames: false
        sync_hosts: true
      -
        type: shell
        inline: |-
          /bin/yum install -y epel-release http://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
          /bin/yum install -y puppet-agent
          /opt/puppetlabs/bin/puppet config set --section main server master.opstheater.vm
          /sbin/service puppet stop

  foss-puppet-agent-el6:
    provisioners:
      -
        type: hosts
        add_localhost_hostnames: false
        sync_hosts: true
      -
        type: shell
        inline: |-
          /usr/bin/yum install -y epel-release http://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm
          /usr/bin/yum install -y puppet-agent
          /opt/puppetlabs/bin/puppet config set --section main server master.opstheater.vm
          /sbin/service puppet stop

  foss-puppet-agent-rhel7:
    provisioners:
      -
        type: hosts
        add_localhost_hostnames: false
        sync_hosts: true
      -
        type: shell
        inline: |-
          /bin/yum install -y epel-release http://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
          /bin/yum install epel-release
          /bin/yum install -y puppet-agent
          /opt/puppetlabs/bin/puppet config set --section main server master.opstheater.vm
          /opt/puppetlabs/bin/puppet agent -t --noop
          /opt/puppetlabs/bin/puppet resource service puppet ensure=running
          /opt/puppetlabs/bin/puppet module install pcfens/filebeat
          /opt/puppetlabs/bin/puppet module install /vagrant/files/puppet-icinga2.tar.gz --ignore-dependencies
          /opt/puppetlabs/bin/puppet apply /vagrant/manifests/base/rhel/rhel7.pp
          /sbin/service puppet stop
