---
vms:
## puppet enterprise master
- name: master
  box: puppetlabs/centos-7.0-64-nocm
  private_networks: [ {ip: '10.20.1.10'} ]
  hostname: master.opstheater.vm
  roles:
  - pe-puppet-master

## FOSS puppet master
- name: foss-master
  box: puppetlabs/centos-7.0-64-nocm
  private_networks: [ {ip: '10.20.1.10'} ]
  hostname: master.opstheater.vm
  roles:
  - foss-puppet-master

## icinga server
- name: icinga2
  box: puppetlabs/centos-7.0-64-nocm
  private_networks: [ {ip: '10.20.1.20'} ]
  hostname: icinga2.opstheater.vm
  roles:
  - foss-puppet-agent-rhel7

## elasticsearch + kibana
- name: elasticsearch
  box: puppetlabs/centos-6.6-64-nocm
  private_networks: [ {ip: '10.20.1.30'} ]
  hostname: elasticsearch.opstheater.vm
  roles:
  - foss-puppet-agent-rhel6

## gitlab + gitlabci + matter most
- name: gitlab
  box: puppetlabs/centos-7.0-64-nocm
  private_networks: [ {ip: '10.20.1.50'} ]
  hostname: gitlab.opstheater.vm
  roles:
  - foss-puppet-agent-rhel7

## mysql
- name: mysql
  box: puppetlabs/centos-7.0-64-nocm
  private_networks: [ {ip: '10.20.1.60'} ]
  hostname: mysql.opstheater.vm
  roles:
  - foss-puppet-agent-rhel7

- name: peclient
  box: puppetlabs/centos-7.0-64-nocm
  private_networks: [ {ip: '10.20.1.200'} ]
  hostname: peclient.opstheater.vm
  roles:
  - pe-puppet-agent

- name: fossclient-rhel7
  box: puppetlabs/centos-7.0-64-nocm
  private_networks: [ {ip: '10.20.1.201'} ]
  hostname: fossrhel7.opstheater.vm
  roles:
  - foss-puppet-agent-rhel7

- name: fossclient-rhel6
  box: puppetlabs/centos-6.6-64-nocm
  private_networks: [ {ip: '10.20.1.203'} ]
  hostname: fossrhel6.opstheater.vm
  roles:
  - foss-puppet-agent-rhel6

- name: fossclient-ubuntutrusty
  box: puppetlabs/ubuntu-14.04-64-nocm
  private_networks: [ {ip: '10.20.1.202'} ]
  hostname: fosstrusty.opstheater.vm
  roles:
  - foss-puppet-agent-trusty
